"""
Django settings for ay_connect project.

Generated by 'django-admin startproject' using Django 4.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""


APP_VERSION = "1.0.2"





CURRENT_DB_ENGINE = ''


from pathlib import Path
import os
import environ
import ldap
from django_auth_ldap.config import LDAPSearch

env = environ.Env()
environ.Env.read_env()
ENV = env('ENV')

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


DJANGO_DRF_FILEPOND_UPLOAD_TMP = os.path.join(BASE_DIR, 'media','filepond-temp-uploads')
DJANGO_DRF_FILEPOND_FILE_STORE_PATH =  os.path.join(BASE_DIR, 'media','stored_uploads')
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-f8k)eq6szikr6@(-$=$o0&dtfgp)ycvogbjq$gbs)4eo8f1st7'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# try:
#     ALLOWED_HOSTS = os.environ.get("ALLOWED_HOSTS").split(" ")
    
# except:
#     ALLOWED_HOSTS = ['192.168.57.90','localhost','127.0.0.1']
#     # ALLOWED_HOSTS = []


# ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'rest_framework',
    'django_filters',
    'import_export',
    'rest_framework.authtoken',
    'core',
    'simple_history',
    
    'rest_framework_datatables',
    'accounts',
    'crequest',
    'setup',
    'sequences.apps.SequencesConfig',
    'django_drf_filepond',
    "sslserver",
    
    "pricelist_update",
    "hr"
]

AUTH_USER_MODEL='hr.CustomUser'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',


    'django.middleware.common.CommonMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'simple_history.middleware.HistoryRequestMiddleware',
    'crequest.middleware.CrequestMiddleware',
    

    'core.middleware.CustomSessionVarHandler',
]


CORS_ALLOWED_ORIGINS = [
    "http://localhost:52667",
    # Add other allowed origins as needed
]



if env('DEBUG_TOOLBAR') == 'Y':
    INSTALLED_APPS += [
        "debug_toolbar",
    ]

    MIDDLEWARE += [
        "debug_toolbar.middleware.DebugToolbarMiddleware",
    ]
    INTERNAL_IPS = [
        # ...
        "127.0.0.1",
        # ...
    ]



X_FRAME_OPTIONS = 'SAMEORIGIN'

ROOT_URLCONF = 'ay_connect.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'debug': True,
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.variables',
            ],
        },
    },
]

WSGI_APPLICATION = 'ay_connect.wsgi.application'

default_app_config = 'hr.apps.HrConfig'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases


DATABASES = {
    'default': {
        'ENGINE': env('DATABASE_ENGINE'),
        'NAME':  env('DATABASE_NAME'),
        'USER': env('DATABASE_USER'),
        'PASSWORD': env('DATABASE_PASSWORD'),
        'HOST':  env('DATABASE_HOST'),
        'PORT': env('DATABASE_PORT')
    }
}

# DATA_UPLOAD_MAX_NUMBER_FIELDS = 10240 # higher than the count of fields
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10 MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10 MB


# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.oracle', 
#         'NAME': 'CLOUDDEV',
#         'USER': 'apps',
#         'PASSWORD': 'apps321',
#         'NAME': """(DESCRIPTION =
#     (ADDRESS = (PROTOCOL = TCP)(HOST = 172.202.3.74)(PORT = 1521))
#     (CONNECT_DATA =
#       (SERVER = DEDICATED)
#       (SERVICE_NAME = UAYSUF)
#     )
#   )""",   # Or an IP Address that your DB is hosted on
#         # 'PORT': '3306',
#     }
# }


# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }
# DATABASES = {    'default': {        'ENGINE': 'django.db.backends.mysql',        'NAME': 'ay_connect',        'USER': 'root',        'PASSWORD': '',        'HOST': 'localhost',        'PORT': '3306'    }}

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/


STATIC_URL = '/static/'
# STATIC_ROOT = os.path.join(BASE_DIR,'static')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'), BASE_DIR / "static",
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LDAP_URL= env('LDAP_URL')
AUTH_LDAP_START_TLS = False
AUTH_LDAP_ALWAYS_UPDATE_USER = False
AUTH_LDAP_SERVER_URI = LDAP_URL
AUTH_LDAP_BIND_DN = ''
AUTH_LDAP_BIND_PASSWORD = ''
AUTH_LDAP_USER_SEARCH = LDAPSearch("DC=alyousuf,DC=net",
                                   ldap.SCOPE_SUBTREE, "(sAMAccountName=%(user)s)")
AUTH_LDAP_CONNECTION_OPTIONS = {
    ldap.OPT_REFERRALS: 0,
}

AUTH_LDAP_USER_ATTR_MAP = {
    "first_name": "givenName",
    "last_name": "sn",
    "email": "mail",
    "photo": "thumbnailPhoto",
    "emp_id": "employeeID"
}

AUTHENTICATION_BACKENDS = (
    # 'django_auth_ldap.backend.LDAPBackend',
    'django.contrib.auth.backends.ModelBackend',
    'accounts.auth_backend.ForceAuth'
)
LOGIN_URL = '/'

REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework_datatables.renderers.DatatablesRenderer',
    ),
    'DEFAULT_FILTER_BACKENDS': (
        'rest_framework_datatables.filters.DatatablesFilterBackend',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework_datatables.pagination.DatatablesPageNumberPagination',
    'PAGE_SIZE': 50,
}


MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR.joinpath("media/")


FILE_UPLOAD_MAX_MEMORY_SIZE = 104857600

ADMIN_EMAIL = 'farhanabadubhai@gmail.com'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

EMAIL_HOST = env('EMAIL_HOST')
EMAIL_PORT = env('EMAIL_PORT')
EMAIL_USE_TLS = env('EMAIL_USE_TLS')
EMAIL_PORT = env('EMAIL_PORT')
EMAIL_HOST_USER = env('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD')
FROM_EMAIL = env('FROM_EMAIL')
DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL')

CHATTER_URL = env('CHATTER_URL')
COMMON_AUTH_SECRET_KEY = env("COMMON_AUTH_SECRET_KEY")
